AWSTemplateFormatVersion: 2010-09-09
Description: >-
  gemini-stream
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  Region:
    Type: String
    Default: ap-south-1  # Set default to your preferred region
    Description: "AWS Region to deploy the Lambda function"
  GeminiApiKey:
    Type: String
    Description: "Api key for the gemini api"
    Default: "AIzaSyAS16s4tCsVo1Kw4N_3OTRz-aSGu2c8kUc"

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: hello-from-lambda.js
  GeminiStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/gemini-stream.geminiStream
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Environment:
        Variables:
          GEMINI_API_KEY : !Ref GeminiApiKey
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
        Cors:
          AllowMethods: ["POST"]  # You can also allow other methods if needed
          AllowOrigins: ["*"]
          AllowHeaders: ["*"]
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON

Outputs:
  MyFunctionUrlEndpoint:
      Description: "My Lambda Function URL Endpoint"
      Value:
        Fn::GetAtt: GeminiStreamFunctionUrl.FunctionUrl
